import {test,expect} from '@playwright/test';
test('real entry has honest empty state and no demo routes or fake playback',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:/A new perspective/})).toBeVisible();
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeDisabled();
 await expect(page.getByRole('button',{name:'Export',exact:true})).toBeDisabled();
 await page.getByText('Get started',{exact:true}).click();
 await expect(page.getByText(/Install the Flute package/)).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
});
test('one product shell preserves real context/state through seek and invalid-source recovery',async({page})=>{
 let requests=0;page.on('request',request=>{if(request.url().endsWith('/data.json'))requests++});
 await page.goto('/tests/preview/fixture.html');
 // A real request is supplied by the fixture, not by the preview renderer.
 await expect(page.getByRole('heading',{name:'Provider content'})).toBeVisible();
 await page.getByRole('button',{name:'Count 0',exact:true}).click();
 await page.evaluate(()=>{(window as any).originalHost=document.querySelector('[data-testid="host"]')});
 const seek=page.getByRole('slider',{name:'Scene time'});
 await seek.fill('4000');
 await expect(page.getByTestId('scene-time')).toHaveText('0:04 / 0:08');
 const transform=await page.locator('[data-flute-stage]').getAttribute('style');
 await page.getByRole('button',{name:'Invalid source',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('last valid');
 expect(await page.locator('[data-flute-stage]').getAttribute('style')).toBe(transform);
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeDisabled();
 await expect(page.evaluate(()=>{(window as any).__FLUTE_CAPTURE__.seek(1000)})).rejects.toThrow();
 await page.getByRole('button',{name:'Correct source',exact:true}).click();
 await expect(page.getByRole('alert')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Count 1',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>(window as any).originalHost===document.querySelector('[data-testid="host"]'))).toBe(true);
 expect(requests).toBe(1);
 await page.evaluate(async()=>{await (window as any).__FLUTE_CAPTURE__.seek(2000)});
 await expect(seek).toHaveValue('2000');
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled();
 await expect(page.locator('[data-flute-capture="scene"]')).toHaveAttribute('data-flute-valid','true');
 await seek.fill('8000');
 await page.getByRole('button',{name:'Replay',exact:true}).click();
 await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await page.getByRole('button',{name:'Restart',exact:true}).click();
 await expect(seek).toHaveValue('0');
 await page.locator('.flute-export summary').click();
 await page.getByRole('combobox',{name:'Export frame rate'}).selectOption('30');
 await expect(page.locator('.flute-export-panel code')).toContainText('--fps 30');
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(page.getByRole('button',{name:'Play',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
});
