import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
export type Metrics={revenue:string;customers:string;growth:string;bars:number[];projects:string[]};
const Context=createContext<Metrics|null>(null);
export function DashboardProvider({children}:{children:ReactNode}){
 const [metrics,setMetrics]=useState<Metrics|null>(null);const [error,setError]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/metrics.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(setMetrics).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>controller.abort()},[]);
 return <Context.Provider value={metrics}>{error?<p role="alert">Metrics unavailable. Reload to retry.</p>:children}</Context.Provider>;
}
export function Sidebar(){return <aside className="orbit-sidebar"><div className="orbit-logo">◒ <strong>orbit</strong></div><span className="orbit-label">WORKSPACE</span><nav>{['Overview','Analytics','Customers','Projects','Messages','Settings'].map((label,i)=><button key={label} className={i===0?'active':''} onClick={e=>{e.currentTarget.parentElement?.querySelector('.active')?.classList.remove('active');e.currentTarget.classList.add('active')}}><span>{['◫','▥','◎','▤','◌','⚙'][i]}</span>{label}</button>)}</nav><div className="orbit-person"><span>AM</span><div>Alex Morgan<small>Personal workspace</small></div></div></aside>}
export function Revenue(){const data=useContext(Context);const [period,setPeriod]=useState('This month');return <section className="orbit-card orbit-revenue"><div className="orbit-card-title"><span>Revenue overview</span><button onClick={()=>setPeriod(v=>v==='This month'?'Last month':'This month')}>{period}⌄</button></div><h2>{data?.revenue??'—'} <small>↗ 18.6%</small></h2><p>Your business, moving forward.</p><div className="orbit-chart">{(data?.bars??[]).map((height,i)=><div key={i} style={{height:height+'%'}}><span>{i+1}</span></div>)}</div><footer>JUN 01 <span>JUN 30</span></footer></section>}
export function Customers(){const data=useContext(Context);return <section className="orbit-card"><span className="orbit-muted">Total customers</span><h2>{data?.customers??'—'}</h2><span className="orbit-positive">↗ 12.8% this month</span><div className="orbit-avatars">{['JL','KM','AS','TW','+8k'].map(t=><span key={t}>{t}</span>)}</div></section>}
export function Projects(){const data=useContext(Context);const [checked,setChecked]=useState<string[]>([]);return <section className="orbit-card"><div className="orbit-card-title">Recent projects <span className="orbit-muted">View all ↗</span></div>{data?.projects.map((name,i)=><label className="orbit-project" key={name}><input type="checkbox" checked={checked.includes(name)} onChange={()=>setChecked(v=>v.includes(name)?v.filter(x=>x!==name):[...v,name])}/><span>{name}<small>{['Due tomorrow','In progress','In review'][i]}</small></span><b>{['↗','◐','◌'][i]}</b></label>)}</section>}
export function Heading(){return <header className="orbit-heading"><div><span className="orbit-muted">MONDAY, JUNE 23</span><h1>Welcome back, Alex <span>↗</span></h1><p>Here’s what’s happening with your business today.</p></div><input placeholder="Search anything…" aria-label="Search dashboard"/></header>}
export function Dashboard(){return <div className="orbit-dashboard"><Sidebar/><main className="orbit-main"><Heading/><div className="orbit-grid"><Revenue/><div className="orbit-side"><Customers/><Projects/></div></div></main></div>}
