import { z } from "zod";
import { RESOURCES } from "../core/resources";
import { FLUTE_BRAND } from "../core/branding";
import { ProjectResultSchema, ProjectStateSchema, type ProjectResult, type ProjectState } from "../core/project";
import * as services from "./services";
import { fault } from "./errors";
import { generatedPreview, htmlEntry, inspectConfig, inspectEntry } from "./vite";

/** SOURCE OF TRUTH: executeProjectCommand trusted project operations.
 * WHAT: validate RESOURCES inputs, host compatibility, integration identity and recovery state.
 * WHY: CLI and later adapters share policy before any scoped mutation.
 * WHERE: core/project owns public contracts; vite owns pure source adaptation; services owns effects.
 */
const PackageSchema = z.object({
  name: z.string().optional(), version: z.string().optional(), packageManager: z.string().optional(),
  workspaces: z.unknown().optional(),
  dependencies: z.record(z.string(), z.string()).optional(),
  devDependencies: z.record(z.string(), z.string()).optional(),
  scripts: z.record(z.string(), z.string()).optional(),
  exports: z.unknown().optional(),
});
const PendingSchema = z.strictObject({ project: ProjectStateSchema, original: z.string() });
const statePath = ".flute/project.json";
const pendingPath = ".flute/pending.json";
/** SOURCE OF TRUTH: agentHandoff, init-project generated agent entry.
 * WHAT: a discoverable pointer and prompt derived from the canonical installed authoring guide.
 * WHY: agents read current policy through RESOURCES without duplicated guidance or config edits.
 * WHERE: initialize journals the FLUTE.md write through services; CLI presents returned metadata.
 */
function agentHandoff() {
  const guide = RESOURCES["authoring-guide"]();
  const handoff = {
    path: "FLUTE.md" as const,
    guideCommand: "npx flute guide --json" as const,
    guideVersion: guide.version,
    prompt: "Read FLUTE.md and run npx flute guide --json in this project. Create a Flute scene using the existing UI from this host page: <page route or component path>. Follow the installed guide, then show the scene in this app's running preview.",
  };
  const text = `<!-- flute:agent-handoff:v1 -->
# ${FLUTE_BRAND.title}

${FLUTE_BRAND.url}

Generated by Flute init. Authoring guide format: ${handoff.guideVersion}.

From this project root, run \`${handoff.guideCommand}\` and read the returned workflow and capabilities.api before authoring. That command reads this installed version's canonical guide; it owns the scene instructions and examples.

Use the installed \`@webprodigies/flute\` and \`@webprodigies/flute/preview\` exports and their TypeScript declarations for the exact API. This app's recipe directory is \`src/flute/scenes\`; read capabilities.api.recipes in the guide for its file contract.

Tell your coding agent the desired host page route or component path, together with this file. Run \`npx flute scenes --json\` to inspect the app's catalog and \`npx flute open --url <running-app-origin>\` to open its existing dev server.
`;
  return { handoff, text };
}
const configs = ["vite.config.ts", "vite.config.js", "vite.config.mts", "vite.config.mjs", "vite.config.cts", "vite.config.cjs"];
const locks = ["package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml", "bun.lock", "bun.lockb"];
function decode<T>(text: string, schema: z.ZodType<T>, target: string): T {
  try { return schema.parse(JSON.parse(text)); }
  catch { throw fault("invalid-file", "Invalid or conflicting project metadata; review " + target + ".", target); }
}
async function packageAt(root: string, target: string) {
  const source = await services.readText(root, target);
  return source === undefined ? undefined : decode(source, PackageSchema, target);
}
async function inspectProject(root: string) {
  // Preflight every mutation/config target, including unused conflicting lock/config candidates.
  for (const target of [statePath, pendingPath, "package.json", ...locks, ...configs, "node_modules/@webprodigies/flute/package.json"])
    await services.scopedPath(root, target);
  const pkg = await packageAt(root, "package.json");
  if (!pkg) throw fault("unsupported-project", "Choose an existing npm Vite React project containing package.json.");
  if (pkg.workspaces !== undefined || (pkg.packageManager && !/^npm@\d/.test(pkg.packageManager)))
    throw fault("unsupported-project", "Automatic setup supports a single-root npm project; adapt this package manager/workspace manually.");
  const existingLocks: string[] = [];
  for (const target of locks) if (await services.readText(root, target) !== undefined) existingLocks.push(target);
  if (existingLocks.some(lock => !["package-lock.json", "npm-shrinkwrap.json"].includes(lock)) || existingLocks.length > 1)
    throw fault("unsupported-project", "Resolve conflicting or non-npm lockfiles before setup.");
  const dependencies = { ...pkg.devDependencies, ...pkg.dependencies };
  if (!dependencies.vite || !/^([~^])?19\.2\.\d+$/.test(dependencies.react ?? "")
    || !/^([~^])?19\.2\.\d+$/.test(dependencies["react-dom"] ?? "")
    || !/^vite(?:\s+--host(?:[ =](?:localhost|127\.0\.0\.1|\[::1\]))?)?(?:\s+--port[ =]\d+)?(?:\s+--strictPort)?$/.test(pkg.scripts?.dev ?? ""))
    throw fault("unsupported-project", "Automatic setup requires React/react-dom 19.2.x, Vite and a standard npm dev script (vite).");
  const found: string[] = [];
  for (const target of configs) {
    const source = await services.readText(root, target);
    if (source !== undefined) { found.push(target); inspectConfig(source, target); }
  }
  if (found.length > 1) throw fault("unsupported-project", "Multiple Vite configuration files are ambiguous.");
  if (!found.length) throw fault("unsupported-project", "Use a static Vite configuration with a standard React plugin for scene refresh.");
  const html = await services.readText(root, "index.html");
  if (html === undefined) throw fault("unsupported-project", "Expected index.html at the project root.");
  const entry = services.relativeTarget(htmlEntry(html));
  const source = await services.readText(root, entry);
  if (source === undefined) throw fault("unsupported-project", "The index.html module entry is missing.", entry);
  return { entry, source, pkg };
}
async function hostDependenciesValid(root: string) {
  for (const name of ["react", "react-dom"]) {
    const installed = await packageAt(root, "node_modules/" + name + "/package.json");
    if (!installed?.version || !/^19\.2\.\d+$/.test(installed.version))
      throw fault("missing-installation", `Missing or incompatible installed ${name}. Run npm install in this project's root to install its declared React 19.2.x dependencies, then retry npx flute init.`, "node_modules/" + name + "/package.json");
  }
}
async function installationValid(root: string, requireToolkit = true) {
  const pkg = await packageAt(root, "package.json");
  await hostDependenciesValid(root);
  const toolkit = await packageAt(root, "node_modules/@webprodigies/flute/package.json");
  if (!toolkit) {
    if (requireToolkit) throw fault("missing-installation", "Flute is not installed. Install your local Flute .tgz with npm install /path/to/flute.tgz, then run npx flute init.");
    return false;
  }
  if (toolkit.name !== "@webprodigies/flute" || !(pkg?.dependencies?.["@webprodigies/flute"] || pkg?.devDependencies?.["@webprodigies/flute"]))
    throw fault("conflict", "Flute installation must match a declared @webprodigies/flute dependency.");
  const exports = toolkit.exports;
  const preview = exports && typeof exports === "object" && !Array.isArray(exports) ? (exports as Record<string, unknown>)["./preview"] : undefined;
  const target = typeof preview === "string" ? preview
    : preview && typeof preview === "object" && !Array.isArray(preview) ? (preview as Record<string, unknown>).import : undefined;
  if (typeof target !== "string" || !target.startsWith("./")
    || await services.readText(root, "node_modules/@webprodigies/flute/" + target.slice(2)) === undefined)
    throw fault("missing-installation", "Installed @webprodigies/flute lacks the preview entry. Install the supported Flute package and retry.");
  return true;
}
async function sourceForInstall(root: string, source: string | undefined) {
  if (!source) throw fault("package-unavailable", "Install Flute in this app with npm install @webprodigies/flute, then run npx flute init. For a local source build, supply --package with its .tgz file.");
  if (!source.endsWith(".tgz") || source.startsWith("-") || source.includes("://"))
    throw fault("invalid-input", "Package source must be an explicit local .tgz file.");
  return services.localPackageSource(root, source);
}
async function stateFor(root: string) {
  const text = await services.readText(root, statePath);
  return { text, project: text === undefined ? undefined : decode(text, ProjectStateSchema, statePath) };
}
function checkState(project: ProjectState, entry: string) {
  services.relativeTarget(project.entry);
  if (project.entry !== entry) throw fault("conflict", "Recorded Flute entry differs from index.html; review the integration.", statePath);
}
async function previewAdapterFor(root: string, entry: string) {
  const adapter = generatedPreview(entry);
  // Vite resolves these extensions before an extensionless import. Never let an
  // unrelated sibling shadow the generated component, including JSX/TSX switches.
  for (const extension of ["mjs", "js", "mts", "ts", "jsx", "tsx", "json"]) {
    const candidate = adapter.path.replace(/\.[jt]sx$/, "." + extension);
    if (candidate !== adapter.path && await services.readText(root, candidate) !== undefined)
      throw fault("conflict", "A file conflicts with Flute's preview adapter import. Move or rename it before setup.", candidate);
  }
  const existing = await services.readText(root, adapter.path);
  if (existing !== undefined && existing !== adapter.text)
    throw fault("conflict", "Flute preview adapter already contains different content. Move or rename it, then retry flute init.", adapter.path);
  return { ...adapter, existing };
}
async function initialize(root: string, packageSource: string | undefined): Promise<ProjectResult> {
  const host = await inspectProject(root);
  const adapter = await previewAdapterFor(root, host.entry);
  const adapterText = adapter.existing;
  const generated = agentHandoff();
  const handoffText = await services.readText(root, generated.handoff.path);
  if (handoffText !== undefined && handoffText !== generated.text)
    throw fault("conflict", "FLUTE.md already contains different content. Move or rename it to preserve your document, then retry npx flute init to generate the installed agent handoff.", generated.handoff.path);
  const saved = await stateFor(root);
  const pendingText = await services.readText(root, pendingPath);
  const pending = pendingText === undefined ? undefined : decode(pendingText, PendingSchema, pendingPath);
  if (saved.project) checkState(saved.project, host.entry);
  if (pending) {
    checkState(pending.project, host.entry);
    if (saved.project && saved.project.projectId !== pending.project.projectId)
      throw fault("conflict", "Pending setup belongs to another project identity.", pendingPath);
  }
  const project = saved.project ?? pending?.project ?? ProjectStateSchema.parse({
    version: 1, projectId: services.newProjectId(), entry: host.entry, packageManager: "npm",
  });
  const adapted = inspectEntry(host.source, host.entry, project.projectId);
  if (pending) {
    const planned = inspectEntry(pending.original, host.entry, project.projectId);
    if ((planned.integrated && !saved.project) || (host.source !== pending.original && adapted.text !== planned.text))
      throw fault("conflict", "Entry changed during interrupted setup; restore the pending original or complete integration before retrying.", host.entry);
  } else if (saved.project && !adapted.integrated) {
    throw fault("conflict", "Recorded project no longer contains its Flute integration; review entry changes.", host.entry);
  }
  let installed = false;
  // Host dependency failures must not be disguised as a missing Flute tarball.
  await hostDependenciesValid(root);
  try { installed = await installationValid(root, false); }
  catch (error) {
    if (!packageSource || !(error instanceof Error) || !("code" in error)
      || !["missing-installation", ...(pending ? ["conflict", "invalid-file"] : [])].includes(String(error.code))) throw error;
  }
  const installSource = installed ? undefined : await sourceForInstall(root, packageSource);
  if (saved.project && adapted.integrated && adapted.text === host.source && !pending && installed
    && handoffText === generated.text && adapterText === adapter.text)
    return { success: true, data: { project, changed: false, handoff: generated.handoff } };
  const journal = pendingText ?? JSON.stringify({ project, original: host.source }, null, 2) + "\n";
  if (!pendingText) await services.atomicWrite(root, pendingPath, journal, undefined);
  if (installSource) {
    await services.installPackage(root, installSource);
    await installationValid(root);
  }
  // Recheck host/config after npm, which may have changed files or been interrupted.
  const after = await inspectProject(root);
  if (after.entry !== host.entry || after.source !== host.source)
    throw fault("conflict", "Project entry changed during installation; retry after reviewing it.", host.entry);
  // The journal covers this generated dependency too. Recheck before other generated writes;
  // create-only transport and exact bytes permit retry after an adapter/entry interruption.
  if ((await previewAdapterFor(root, host.entry)).existing !== adapterText)
    throw fault("conflict", "Flute preview adapter changed during setup; review it before retrying.", adapter.path);
  // Write before entry/state, so a handoff conflict cannot commit an incomplete setup.
  // An interruption after this write resumes by recognizing the exact generated bytes.
  if (handoffText === undefined) await services.atomicWrite(root, generated.handoff.path, generated.text, undefined);
  else if (await services.readText(root, generated.handoff.path) !== generated.text)
    throw fault("conflict", "FLUTE.md changed during setup; review it before retrying npx flute init.", generated.handoff.path);
  if (adapterText === undefined) await services.atomicWrite(root, adapter.path, adapter.text, undefined);
  if (adapted.text !== host.source) await services.atomicWrite(root, host.entry, adapted.text, host.source);
  const state = JSON.stringify(project, null, 2) + "\n";
  if (!saved.project) await services.atomicWrite(root, statePath, state, saved.text);
  await services.removeText(root, pendingPath, journal);
  return { success: true, data: { project, changed: true, handoff: generated.handoff } };
}
async function load(root: string) {
  const host = await inspectProject(root);
  const saved = await stateFor(root);
  if (!saved.project) throw fault("not-initialized", "Run flute init in this project first.");
  checkState(saved.project, host.entry);
  if (await services.readText(root, pendingPath) !== undefined)
    throw fault("incomplete-setup", "Setup was interrupted. Run flute init again to resume safely.");
  const adapted = inspectEntry(host.source, host.entry, saved.project.projectId);
  if (!adapted.integrated)
    throw fault("conflict", "The recorded Flute integration is missing.", host.entry);
  if (adapted.text !== host.source)
    throw fault("incomplete-setup", "Run flute init to upgrade the installed preview refresh boundary.", host.entry);
  const adapter = await previewAdapterFor(root, host.entry);
  if (adapter.existing !== adapter.text)
    throw fault("conflict", "The generated preview adapter is missing or changed. Review it and run flute init.", adapter.path);
  await installationValid(root);
  return saved.project;
}
async function openPreview(root: string, input: z.output<typeof RESOURCES["open-preview"]>) {
  const project = await load(root);
  // Atomic entry edits and npm changes can briefly leave Vite serving its old module.
  // Retry identity checks within a fixed budget; never accept a different project.
  let matched = false;
  for (let attempt = 0; attempt < 5; attempt++) {
    try {
      const html = await services.fetchText(input.url);
      const entry = services.relativeTarget(htmlEntry(html, true));
      if (entry !== project.entry) throw fault("wrong-dev-server", "The dev server belongs to another entry.");
      const transformed = await services.fetchText(new URL("/" + entry, input.url).href);
      if (!transformed.includes(project.projectId) || !transformed.includes("ProjectPreview")
        || !(transformed.includes("@webprodigies_flute_preview") || transformed.includes("@webprodigies/flute/preview") || transformed.includes("/src/flute/ProjectPreview.")))
        throw fault("wrong-dev-server", "Dev server does not contain this project's preview identity.");
      matched = true;
      break;
    } catch {
      if (attempt < 4) await services.pause(150);
    }
  }
  if (!matched) throw fault("missing-dev-server", "No matching Vite dev server at " + input.url + ". Run npm run dev in this project, then retry with its loopback URL. Flute will not start another server or change its port.");
  const url = new URL("/?flute-preview=1", input.url).href;
  if (input.launch) await services.openBrowser(root, url);
  return { success: true as const, data: { project, url } };
}
export async function executeProjectCommand(operation: unknown, input: unknown, context: { root: string }): Promise<ProjectResult> {
  try {
    if (typeof operation !== "string" || !Object.hasOwn(RESOURCES, operation))
      throw fault("invalid-operation", "Unknown project operation.");
    const schema = RESOURCES[operation as keyof typeof RESOURCES];
    if (!("safeParse" in schema)) throw fault("invalid-operation", "This operation is not a project command.");
    const parsed = schema.safeParse(input);
    if (!parsed.success) return ProjectResultSchema.parse({ success: false, issues: parsed.error.issues.map(issue => ({
      code: "invalid-input", message: issue.message, path: issue.path.join("."),
    })) });
    if (!context || typeof context.root !== "string") throw fault("invalid-scope", "Provide an absolute local project root.");
    const root = await services.canonicalRoot(context.root);
    let result: ProjectResult;
    if (operation === "init-project") result = await initialize(root, (parsed.data as z.output<typeof RESOURCES["init-project"]>).packageSource);
    else if (operation === "open-preview") result = await openPreview(root, parsed.data as z.output<typeof RESOURCES["open-preview"]>);
    else result = { success: true, data: { project: await load(root) } };
    return ProjectResultSchema.parse(result);
  } catch (error) {
    const known = error instanceof Error && "code" in error && "target" in error;
    return { success: false, issues: [{
      code: known ? String(error.code) : "project-error",
      message: known ? error.message : "Unable to access the project. Check local files and permissions, then retry.",
      ...(known && typeof error.target === "string" ? { path: error.target } : {}),
    }] };
  }
}
