import type { ProjectState } from "../core/project";

/** SOURCE OF TRUTH: portableIntegration, portableCatalog, framework connection source.
 * WHAT: generate additive host files around the same public ProjectPreview contract.
 * WHY: rendering/catalog policy belongs to React/core; build tools only connect imports and routes.
 * WHERE: project commands validate and write these files; arbitrary React hosts supply their own dev flag.
 */
export function portableIntegration(project: ProjectState, catalog: string): Record<string,string> {
  const files: Record<string,string> = {
    "src/flute/catalog.js": catalog,
    "src/flute/ProjectPreview.jsx": `"use client";
import React from "react";
import { ProjectPreview } from "@webprodigies/flute/preview";
import { sceneModules } from "./catalog";
// Host-owned development flag: no process, Vite or Electron globals in this adapter.
export function FluteProjectPreview({ children, enabled, active, ...props }) {
  if (!enabled) return children;
  return <ProjectPreview {...props} projectId=${JSON.stringify(project.projectId)} enabled={enabled} active={active} sceneModules={sceneModules}>{children}</ProjectPreview>;
}
`,
  };
  if (project.adapter === "react") return files;
  files["src/flute/Studio.jsx"] = `"use client";
import React from "react";
import dynamic from "next/dynamic";
const Preview = process.env.NODE_ENV === "development" ? dynamic(() => import("./ProjectPreview").then(m => m.FluteProjectPreview), { ssr: false }) : () => null;
export default function FluteStudio() {
  return <Preview enabled={process.env.NODE_ENV === "development"} active />;
}
`;
  // Relative route imports work with or without a src directory and without aliases.
  const depth = project.entry.split("/").length - 1;
  const studio = "../".repeat(depth) + "src/flute/Studio";
  if (project.adapter === "next-app") {
    files[project.entry] = `import React from "react";
import { notFound } from "next/navigation";
import FluteStudio from ${JSON.stringify(studio)};
export default function FlutePage() {
  if (process.env.NODE_ENV !== "development") notFound();
  return <><meta name="flute-project" content=${JSON.stringify(project.projectId)} /><FluteStudio /></>;
}
`;
  } else {
    files[project.entry] = `import React from "react";
import FluteStudio from ${JSON.stringify(studio)};
export function getServerSideProps() {
  return process.env.NODE_ENV === "development" ? { props: {} } : { notFound: true };
}
export default function FlutePage() {
  return <><meta name="flute-project" content=${JSON.stringify(project.projectId)} /><FluteStudio /></>;
}
`;
  }
  return files;
}

/** SOURCE OF TRUTH: portableCatalog.
 * WHAT: static module references for bundlers without import.meta.glob.
 * WHY: the bundler owns hot reload; the shared SceneModuleLibrary owns loading and validation.
 * WHERE: sync-project supplies validated recipe/binding paths. Metadata edits hot reload normally;
 * adding/removing file pairs requires flute sync. No arbitrary host modules are executed by the CLI.
 */
export function portableCatalog(entries: {source:string;binding:string}[]): string {
  const imports = entries.map((entry,index) => `import recipe${index} from ${JSON.stringify("./scenes/" + entry.source.split("/").pop())};`);
  const mappings = entries.flatMap((entry,index) => [
    `  ${JSON.stringify(entry.source)}: async () => ({default:recipe${index}}),`,
    `  ${JSON.stringify(entry.binding)}: () => import(${JSON.stringify("./scenes/" + entry.binding.split("/").pop()?.replace(/\.[jt]sx$/, ""))}),`,
  ]);
  return '// Generated by flute sync. Edit recipes and components, not this registry.\n' +
    imports.join("\n") + "\nexport const sceneModules = {\n" + mappings.join("\n") + "\n};\n";
}
